CREATE TABLE [dbo].[PaymentItems]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(127) NOT NULL,
	[Amount] INT NOT NULL DEFAULT 1,
	[Price] DECIMAL(15, 2) NOT NULL, 
	[PaymentId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_PaymentItems_PaymentId FOREIGN KEY REFERENCES Payments(Id)
)
