CREATE TABLE [dbo].[Payments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Currency] VARCHAR(3) NOT NULL,
	[State] SMALLINT NOT NULL DEFAULT 4,
	[Provider] NVARCHAR(MAX) NOT NULL,
	[CreateDate] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
