CREATE TABLE [dbo].[Payments]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Currency] VARCHAR(3) NOT NULL,
	[State] NVARCHAR(MAX) NOT NULL DEFAULT 'Waiting',
	[Provider] NVARCHAR(MAX) NOT NULL,
	[CreateDate] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
